### ISSUE TITLE
it seems do not work offline

### ISSUE THREAD

**Issue by 77bgh** [abacaj/replit-3B-inference#8] opened 2023-06-29 09:13 UTC
it seems it do not work offline, when I put my wifi in plane mode, I receive this error

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/teknium/Replit-v2-CodeInstruct-3B/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000228F9769DE0>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))

**Comment by 77bgh** [comment] 2023-06-29 17:20
Hello, 

I observed that download_model.py downloaded data here C:\Users\myuser\.cache\huggingface\hub

models--abacaj--Replit-v2-CodeInstruct-3B-ggml ( 1.4GB )
models--teknium--Replit-v2-CodeInstruct-3B ( 1,24 KB)  ?? so small

so if I already run inference.py with wifi , then switch off wifi, the script continues to run

however if I switch of wifi, than try inference.py, I receive the above err

I used python download_model.py , than python inference.py , bellow the code

import os
from dataclasses import dataclass, asdict
from ctransformers import AutoModelForCausalLM, AutoConfig


@dataclass
class GenerationConfig:
    temperature: float
    top_k: int
    top_p: float
    repetition_penalty: float
    max_new_tokens: int
    seed: int
    reset: bool
    stream: bool
    threads: int
    stop: list[str]


def format_prompt(user_prompt: str):
    return f"""### Instruction:
{user_prompt}

### Response:"""


def generate(
    llm: AutoModelForCausalLM,
    generation_config: GenerationConfig,
    user_prompt: str,
):
    """run model inference, will return a Generator if streaming is true"""

    return llm(
        format_prompt(
            user_prompt,
        ),
        **asdict(generation_config),
    )


if __name__ == "__main__":
    config = AutoConfig.from_pretrained(
        "teknium/Replit-v2-CodeInstruct-3B", context_length=2048
    )
    llm = AutoModelForCausalLM.from_pretrained(
        os.path.abspath("models/replit-v2-codeinstruct-3b.q4_1.bin"),
        model_type="replit",
        config=config,
    )

    generation_config = GenerationConfig(
        temperature=0.2,
        top_k=50,
        top_p=0.9,
        repetition_penalty=1.0,
        max_new_tokens=512,  # adjust as needed
        seed=42,
        reset=True,  # reset history (cache)
        stream=True,  # streaming per word/token
        threads=int(os.cpu_count() / 6),  # adjust for your CPU
        stop=["<|endoftext|>"],
    )

    user_prefix = "[user]: "
    assistant_prefix = f"[assistant]:"

    while True:
        user_prompt = input(user_prefix)
        generator = generate(llm, generation_config, user_prompt.strip())
        print(assistant_prefix, end=" ", flush=True)
        for word in generator:
            print(word, end="", flush=True)
        print("")

**Comment by abacaj** [comment] 2023-06-29 18:34
Thanks for sharing, the issue is around the config.json file which is used by the AutoConfig class. Just pushed a fix for it to add download of config to models folder. You can call `python download_model.py` to get the config file

**Comment by 77bgh** [comment] 2023-06-29 18:40
yes Indeed , now it;s working offline , well done :)

**Closed** 2023-06-29 18:41 UTC
